### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by SteveDiamond** [TrishGillett/pysdpt3glue#27]
@discardthree thanks so much for making this! I'm sorry for not responding sooner. Having proper SDP solvers will be a huge help.

I ran into some issues installing pysdpt3glue. The first was that installing from pip seemed to require an old version of CVXcanon, which made pip try to reinstall many things. Is this dependency intentional?

The second is that when I cloned the repo and ran setup.py install, it failed because requirements.txt was missing.

I would suggest just putting the dependencies in setup.py.

**Comment by TrishGillett** [comment]
Hi, thanks for coming to check it out!  When we built the package for PyPI we let the requirements.txt be automatically generated by `pip-compile` like this (disclaimer: this is from my current computer and I don't know if it's identical to the one on PyPI):

```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file requirements.txt requirements.in
#

CVXcanon==0.1.0           # via cvxpy
cvxopt==1.1.8
cvxpy==0.4.2
dill==0.2.5               # via multiprocess
ecos==2.0.4               # via cvxpy
fastcache==1.0.2          # via cvxpy
multiprocess==0.70.4      # via cvxpy
numpy==1.11.1
scipy==0.17.1
scs==1.2.6                # via cvxpy
selenium==2.53.6
six==1.10.0               # via cvxpy
toolz==0.8.0              # via cvxpy
```

Since it's fairly conservative, it locked the dependencies to specific versions.  Reasonably we can change many/all of these == to >= and expect to deal with any future incompatibilities as they arise.  And of course, you're correct that it's an oversight that requirements.txt isn't actually in the repo.  ;)

**Comment by SteveDiamond** [comment]
That makes sense. I would change these to >=, like you said.

**Comment by TrishGillett** [comment]
Okay, it's not pushed to PyPI yet so pip installing won't be fixed yet, but git clone + setup.py shouldn't complain about requirements.txt anymore.  By all means post again if you run into other snags. :)
